apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitops-binding
  namespace: myapp
subjects:
- kind: ServiceAccount
  name: default
  namespace: myapp
roleRef:
  kind: Role
  name: edit
  apiGroup: rbac.authorization.k8s.io
