apiVersion: v1
kind: Service
metadata:
  name: nodeapp-load-balancer-service
  namespace: myapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: myapp
    type: front-end
